# Welcome to Jekyll!
#

# Site settings
title: YWAM Sendai
description: To know God and to make Him know to North-East Japan
owner: YWAM Sendai # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: info@ywamsendai.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ywamsendai.org" # the base hostname & protocol for your site
theme: minima
medium: https://medium.com/ywamsendai/
join: https://www.ywamsendai.org/join
riot: https://riot.im/app/#/group/+ywamsendai:matrix.org
twitter_username: ywamsendai
github_username:  ywamsendai
facebook_username: ywamsendai
youtube: https://www.youtube.com/channel/UCH4EWvQQGs2VEtYtH_Pr_lw
instagram: https://instagram.com/ywamsendai


# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
sass:
    sass_dir: _sass
#  style: compressed
permalink: /:categories/:title

collections:
  blog:
    output: true

plugins:
  - jekyll-sitemap
  - jekyll-feed
